# Generated by Django 4.1.3 on 2023-01-09 21:28

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_name", models.CharField(max_length=100)),
                ("payroll_code", models.CharField(blank=True, max_length=50)),
                ("ownership", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="community_name"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Communities",
                "ordering": ["community_name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=50, null=True)),
                ("payroll_id", models.CharField(max_length=20, null=True)),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("ER", "Eastern Region"),
                            ("CR", "Central Region"),
                            ("ALL", "All Communities"),
                            ("C", "Home Community"),
                            ("AXA", "All Communities Except Arrow"),
                            ("TRV", "Travel Team"),
                            ("ND", "New Development"),
                            ("M", "Manual"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_community",
                        to="core.community",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["user__last_name"],
            },
        ),
    ]
